name: "releaser"

on:
  push:
    branches:
      - "master"

jobs:
  compile_build_release:
    runs-on: ubuntu-latest
    name: Build the Maven Project
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build and test project
        run: mvn -B verify
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: version
      - name: Extract Maven project name
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.name}' --non-recursive exec:exec)
        id: project
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ steps.project.outputs.version }} v${{ steps.version.outputs.version }}"
          automatic_release_tag: "${{ steps.version.outputs.version }}"
          files: |
            target/${{ steps.project.outputs.version }}-${{ steps.version.outputs.version }}.jar
        id: automatic_releases